"""
Retrieve TheGuardian articles and save them in a .txt file.
"""

def compute_document_length(document):
    return len(document.split())

def compute_average_document_length(list_documents):
    sum_words = 0
    for document in list_documents:
        sum_words = sum_words + len(document.split())
    mean = sum_words / len(list_documents)
    return mean

articles_dataset = [
        'Ukraine’s president has made a desperate appeal to the Russian people asking them to “listen to the voice of '
        'reason” and stop a war he said the Kremlin has already ordered. After Ukraine declared a state of emergency '
        'and started calling up reservists, Volodymyr Zelenskiy delivered a 10-minute video address in the early '
        'hours of Thursday morning, saying Vladimir Putin had not taken his call. “Today I initiated a phone call '
        'with the president of the Russian Federation. The result was silence,” Zelenskiy said. For months, '
        'the Ukrainian president had played down the threat of invasion as alarmist, but by Thursday he was convinced '
        'that Europe was the brink of a horrendous new conflict. “We are separated by more than 2,000 km of mutual '
        'borders, along which 200,000 of your soldiers and a thousand armoured vehicles are standing. Your leadership '
        'has approved their step forward on to the territory of another country. This step could become the beginning '
        'of a big war,” Zelenskiy said. “They’re telling you that this flame will liberate the people of Ukraine, '
        'but the Ukrainian people are free.” Ukraine called an emergency session of the UN security council to '
        'confront Russia which, by irony of the rota, will be chairing the meeting. Meanwhile Zelenskiy’s approach '
        'was to try to speak directly to ordinary Russians, on a video uploaded to Telegram messaging app, '
        'over the heads of the Kremlin, predicting that the Russian media would not broadcast it. “I know this speech '
        'of mine won’t be shown on Russian TV, but the people of Russia need to see it,” the Ukrainian president '
        'said. They need to know the truth. The truth is that this must be stopped before it is too late.” “Listen to '
        'yourselves, to the voice of reason. The people of Ukraine want peace,” Zelenskiy said. But he added: “if '
        'someone attempts to take away our land, our freedom, our lives, the lives of our children, we will defend '
        'ourselves.” “By attacking, you will see our faces, not our backs, but our faces,” he said. Early on Thursday '
        'morning, Russia issued an alert warning all civilian aviation to stay out of the air space over the border '
        'between Russia and northeast Ukraine. As it manoeuvred its forces ever closer to the border and arrayed them '
        'in attack formation, the Kremlin announced it had received a request from the leaders of the small '
        'Moscow-run enclaves in east Ukraine asking for urgent assistance “to avoid civilian casualties and a '
        'humanitarian catastrophe”. Putin secured formal backing from Russia parliament on Tuesday, to deploy Russian '
        'forces beyond the country’s borders. For several days, Putin and his aides had been claiming there was a '
        '“genocide” of Russian speakers under way in the Donbas region, in the absence of any evidence. Dossiers of '
        'supposed evidence circulated at the UN and to the media, largely consisted of improvised burial sites of '
        'civilian casualties from shelling over the eight-year conflict there. Many of the dead referred to in the '
        'Russian dossier had died in the first year of fighting in 2014, when there were substantial civilian '
        'casualties on both sides of the frontline. According to several media reports, confirmed by the Guardian, '
        'the White House has warned the Zelenskiy government to expect a large-scale offensive in the next 48 hours. '
        'The north-eastern city of Kharkiv, 40kms from the border with Russia, is at particular risk, Newsweek CNN '
        'reported, citing US intelligence. “They have advanced their readiness where they are literally ready to go '
        'now if they get the order to go now,” a senior US defence official told reporters. “We assess today that he '
        '[Putin] is near 100% of all the forces we anticipated he would move in,” the official said, adding that 80% '
        'of those forces were in combat-ready positions. “They have plans to use reserves and their equivalent of the '
        'national guard. The implication would be that they have long-term goals here.” The Biden administration’s '
        'predictions of imminent attack have been wrong before, with a date given of last Wednesday – 16 February. '
        'But US, UK and Ukrainian officials all concur that Putin has to move in the next few days, '
        'or risk exhausting his troops waiting on the border.\n“We are potentially close to some sort of action,'
        '” the Pentagon spokesperson, John Kirby, said on Wednesday evening, adding: “Russian forces continue to '
        'assemble closer to the border.” Kirby said that Putin “is going to have to answer to Russian moms and dads '
        'about their soldiers that aren’t making it back home alive or making it back with injuries.”\nOn Wednesday, '
        'Ukraine prepared its population for the prospect of a devastating war. The country’s parliament voted to '
        'approve a state of emergency, which allows authorities to impose curfews and restrictions on movement, '
        'block rallies and ban political parties and organisations. Some 36,000 reservists were mobilised, '
        'and a law was passed allowing Ukrainians to carry personal firearms, as many queued to purchase AR-15s and '
        'sniper rifles at local gun shops. Airports in the eastern Ukrainian cities of Kharkiv, Dnipro, '
        'and Zaporizhzhia closed their air space, and the nearly 3 million Ukrainians still in Russia were told to '
        'leave as soon as possible, warned that their government might not be able to help them much longer. The '
        'Ukrainian government said a massive cyber-attack had targeted ministries and banks on Wednesday. Officials '
        'have warned that Russia could use elements of hybrid warfare to sow confusion before launching an all-out '
        'military assault. Russia began evacuating its embassy in Kyiv on Wednesday to “protect the lives and safety '
        '[of diplomats]” [of diplomats]. Diplomats were filmed walking quickly with their luggage to waiting cars and '
        'smoke was observed emerging from the grounds in a possible effort to burn sensitive documents. The Russian '
        'flag was lowered. On the same day, EU countries approved tough new sanctions on Russian officials and '
        '“propagandists” , imposing asset freezes and travel bans on Russia’s defence minister, Sergei Shoigu, '
        'foreign ministry spokeswoman, Maria Zakharova, and 351 Duma deputies who voted to recognise the '
        'Russian-controlled territories in east Ukraine. In Washington Joe Biden said he was allowing sanctions to '
        'move forward against the company that built the Russia-to-Germany Nord Stream 2 gas pipeline, a day after '
        'Germany indefinitely suspended the project. But Russia appears unmoved by the diplomatic pressure. In fiery '
        'remarks at the United Nations on Wednesday, ambassador Vasily Nebenzya accused Ukraine of genocide and human '
        'rights violations against those living in Donbas, a claim widely denounced as being as false. Andriy '
        'Zagorodnyuk, Ukraine’s former defence minister, said Putin would have to decide in the next few days whether '
        'to attack Ukraine. “There are two scenarios. One, they engage in some sort of action. The other is they go '
        'for a strategic pause. For now, it’s 50-50.” He said the Russian troops massed in Belarus on Ukraine’s '
        'border were sleeping in tent encampments and were “literally tired”. The longer they stayed in a holding '
        'position the less effective they became, he said. “Either Moscow starts something or they are rotated out,'
        '” he added.\nDenis Pushilin, the leader of the Russian-controlled territory in Donetsk, said on Wednesday '
        'that he would not immediately order an attack on Ukrainian positions on the frontline but would not rule out '
        'a “military solution” to expanding his region’s borders, either. Appearing alongside the head of Russia’s '
        'ruling United Russia party, Pushilin said that Russia and its client state were not yet at the stage of a '
        '“military solution to [expanding] to the region’s borders”. On Wednesday, Putin delivered a video address in '
        'connection with the Defender of the Fatherland Day, a national holiday recognising members of the military '
        'and on which most Russian men receive presents.\nIn the speech, he praised the battle-readiness of Russia’s '
        'military, which has 190,000 soldiers on the borders with Ukraine according to western estimates. “Our '
        'country is always open for direct and honest dialogue, for the search for diplomatic solutions to the most '
        'complex problems,” Putin said. But he added: “The interests of Russia, the security of our citizens, '
        'are non-negotiable for us.”',
        'For many Russians, it was an unfamiliar sight to see the faces of the two leaders of the pro-Kremlin proxy '
        'states in eastern Ukraine pop up on their television screens last Friday, announcing the mass evacuation of '
        'Donbas citizens to Russia. Since then, however, Denis Pushilin and Leonid Pasechnik, heads of the '
        'self-proclaimed republics in Luhansk and Donetsk, have seen their political profiles rocket, culminating on '
        'Monday with the two leaders asking the Russian president, Vladimir Putin, to recognise their “republics”. '
        '“This is their golden hour; they are quickly becoming stars,” said the political analyst Konstantin Skorkin, '
        'a Luhansk native who focuses on the region. Amid reports of Russian tanks rolling into the Donbas, '
        'questions have arisen as to what extent the separatists have been acting on their own accord or are just '
        'pawns in the Kremlin’s bigger geopolitical aims. “They are simply puppets of the Kremlin and the recent '
        'events only confirmed this once again,” said Skorkin.\nHe points to how each statement that the two leaders '
        'made over the past week was quickly picked up by state media and the Kremlin. “The Russian leadership '
        'coordinated everything and nothing was left to chance,” the analyst said. The two regions have been highly '
        'dependent on Russian support since their formation in 2014 as they suffered economic collapse during their '
        'eight years of unrecognised independence. The regions’ People’s Militia is also fully armed by the Russian '
        'state, and Ukrainian officials believe up to 11,000 Russian soldiers are permanently stationed in the '
        'Donbas. “They just simply wouldn’t exist without Russian support,” said Nikolaus von Twickel, former OSCE '
        'staff member in Donetsk who has written extensively on the Donbas. “But their relationship with Moscow has '
        'changed over the years.” In the chaos that followed the 2014 Maidan revolution, a number of rogue and '
        'unpredictable local leaders emerged as heads of the two separatist states. Von Twickel said the Kremlin had '
        'since worked systematically to replace these firebrands with trusted loyalists. Analysts see 2018 as a '
        'turning point in the relative independence of the region, when Alexander Zakharchenko, the head of the '
        'self-proclaimed Donetsk people’s republic, was killed in a car bomb and replaced by the more reliable '
        'Pushilin. The Ukrainian security service said at the time Zakharchenko’s death was a result of an operation '
        'by Russian special forces. “Zacharchenko had his own personal army, and the Donbas even had its own defence '
        'ministry – all of that has disbanded since. It was a clear signal that the rebels will only act according to '
        'Kremlin’s rules,” Von Twickel said. And while experts now point to the very limited autonomy of Pushilin and '
        'Pasechnik, closely following the two leaders can serve as a good indication of what the Kremlin may do next '
        'in Ukraine. Denis Pushilin\nThe younger and more charismatic of the two, not much is known about Pushilin’s '
        'early days in the Donbas. He first came to prominence in 2011, while working for the infamous MMM group, '
        'a notorious Russian Ponzi scheme that is considered to be one of the world’s largest fraud organisations of '
        'all time. “He is your typical wheeler-dealer kind of guy,” said Von Twickel. Pushilin joined the separatist '
        'cause early on in 2014, but in contrast to some of the other Donetsk leaders, he never saw any large '
        'military action, often sporting a suit in public, a habit he was occasionally mocked for by the other '
        'rebels. But over the years, Pushilin looked to have gained the Kremlin’s trust as he became the head of the '
        'region after the murky murder of Zakharchenko. Pushilin has repeatedly expressed his desire for the region '
        'to be part of a “renewed Russian empire” rather than an independent state. “Donbas should be part of the '
        'Russian empire. I don’t see anything bad in imperialism,” he once said. Leonid Pasechnik\nPrior to the 2014 '
        'Maidan revolution, Pasechnik had a long career in the Ukrainian security services, where he rose to the rank '
        'of lieutenant colonel. He first received national attention in 2006 when in a special operation he '
        'intercepted 7.24m Russian roubles in cash (almost £2m) that was being smuggled across the Russian-Ukrainian '
        'border. Pasechnik reportedly refused to take a bribe from the smugglers in the operation, receiving a medal '
        'from the pro-western Ukrainian president, Viktor Yushchenko, for the operation. Like many other generals in '
        'the Ukrainian security services in the Donbas, Pasechnik chose the side of the pro-Russian separatists in '
        '2014, when he headed the notorious state security department of the self-proclaimed Luhansk people’s '
        'republic. “He operated the main prisons and the so-called isolation cells, cellars where pretty sinister '
        'stuff happened,” said Von Twickel, referring to the many media reports depicting stories of torture of those '
        'who opposed the separatists. In 2017, Pasechnik emerged as the victor of a violent power struggle with the '
        'then head of Luhansk, Igor Plotnitsky. Not much has since been heard from the camera-shy and timid '
        'Pasechnik, and he has somewhat looked out of place as he was suddenly sprung into the country’s spotlight.',
        'What is the relationship between Russia’s threats to Ukraine and the gas price crisis? Gas prices are '
        'soaring globally, largely because of the resurgence of demand for fossil fuels after the Covid-19 pandemic '
        'and lockdowns, depleted storage and the difficulty of ramping up supply after the disruptions of the past '
        'two years. But prices have also been significantly affected by Russia’s recent decision to tighten gas '
        'supplies to Europe, which experts believe was driven by Vladimir Putin’s desire to move against Ukraine. '
        'Europe is dependent on Russia for about 40% of its natural gas supplies, and despite the expansion of '
        'renewable energy over the past two decades, that dependency is increasing as countries shift to gas, '
        'away from dirtier coal. Germany is particularly vulnerable, as it has shut down nearly all of its nuclear '
        'power stations and aims to eliminate coal by 2030. A major new gas pipeline, Gazprom’s $11bn Nord Stream 2 '
        'from Russia across the Baltic to Germany, which would heat 26m German homes, has been the focus of Germany’s '
        'diplomatic relations with Russia since it was announced in 2015. Construction on the 1,200km pipeline was '
        'completed last year, but no gas has yet flowed and its future is now in doubt as Germany’s chancellor Olaf '
        'Scholz dramatically halted approval for the project on Tuesday.\nConcerns that Russia is using its gas '
        'supplies as a weapon to achieve its political aims are well founded. Fatih Birol, executive director of the '
        'International Energy Agency, noted that Russia’s decision to drop gas supplies to Europe by a quarter came '
        'as it was heightening tension towards Ukraine. “I hope this was only a coincidence,” he told the Guardian. '
        'Is this really another war over fossil fuels? No. Energy resources are not the focus of this threatened '
        'conflict. Vladimir Putin has a long history of territorial ambitions in former Soviet nations, which he made '
        'explicit this week, and of attempts to exert political control over Ukraine. Putin is said by supporters to '
        'be concerned over the possibility of Nato expansion, although many analysts say this is a pretext. So the '
        'Ukraine crisis is not a war over resources, but it has many implications for resource use. Russia is '
        'effectively weaponising its dominance over European gas supply for political ends. Reducing reliance on '
        'Russian gas is an urgent necessity for the EU to reach net zero emissions, and would also diminish Putin’s '
        'political leverage over the EU. It is also worth noting that in the longer term, as Europe weans itself off '
        'gas and pursues net zero emissions, the value of this political weapon will wane rapidly. Russia’s '
        'industries have never recovered from the fall of communism, and its economy is now based overwhelmingly on '
        'the export of fossil fuels, with much of the rest made up of energy-dependent mineral resources, '
        'such as iron, steel, aluminium and other metals, and some agriculture. Four in 10 roubles accruing to '
        'Russia’s federal budget pre-pandemic came from oil and gas, which made up 60% of Russian exports in 2019. '
        'Kremlin strategists are therefore keenly aware that in the longer term the global move to net zero threatens '
        'the whole basis of Russia’s economy and global influence. Why is Europe so dependent on Russian gas? '
        'Historically, much of Europe was heavily dependent on coal for power and heating. Renewable energy '
        'generation has more than doubled since 2004, and reached 22% of final energy production in 2020. However, '
        'at the same time the share generated from nuclear power has fallen, from about a third of the EU’s '
        'electricity in 1995 to about a quarter today. After the accident at Japan’s Fukushima nuclear power plant in '
        '2011, Germany’s then chancellor Angela Merkel announced an “Energiewende” – an energy shift – that would see '
        'all of the country’s reactors shut down. This has increased Germany’s need for gas, and similar moves away '
        'from coal and towards lower emissions in other countries – including the UK, which despite North Sea gas '
        'production is a net importer of gas – have heightened the dependency. The geopolitical implications of this '
        'dependency, as well as the climate impacts, are now unignorable. Paul Bledsoe, a former Clinton White House '
        'climate adviser, now with the Progressive Policy Institute in Washington DC, says: “It has taken the current '
        'crisis for Germany and the EU to recognise that its co-dependence on Russian gas is a geopolitical and '
        'climate nightmare from which they must finally awake. Reducing Russian gas reliance is a huge climate and '
        'moral imperative that Europe must prioritise.” Will Russia turn off gas supplies to Europe if the EU and the '
        'UK impose sanctions? That would be a momentous move from Russia. Any further reductions of Russian gas '
        'supply to Europe would have severe consequences, for Europe but also for Russia itself. Birol said earlier '
        'this month, before sanctions were imposed: “If Russia stops the gas supply to Europe, it could have a '
        'seismic impact on European energy. [Russia] has to consider the consequences if existing oil and gas '
        'supplies to Europe are halted.” He added: “Failure to maintain [supplies] would shatter Russia’s reputation '
        'as a reliable partner and that would be a tectonic shift. Russia would be seen as a threat and that would '
        'have far-reaching consequences for European economies, but even more consequences for Russia. Europe would '
        'choose a strategy to diverge from Russia.” What impact will Russia’s actions in Ukraine have on climate '
        'diplomacy? Russia was almost invisible at the Cop26 UN climate summit in Glasgow last November, '
        'after a surprising public commitment to reach net zero greenhouse gas emissions by 2060. But the Kremlin has '
        'left the details of the goal vague and shown little sign of updating Russia’s emissions commitments for '
        '2030, which are key to limiting global temperature rises to 1.5C. This is a crucial year for climate '
        'diplomacy, as the pledges from all countries in Glasgow are still inadequate for the 1.5C goal, and the UK '
        'Cop26 presidency is hoping for major progress before the next UN climate meeting in Egypt this November. '
        'Russia’s stance on Ukraine will certainly have an impact on those discussions, not least as any conflict '
        'will focus attention on the move from fossil fuels. It is also notable that Russia’s oil and gas operations '
        'are among the worst in the world for the climate. Data released this week by the IEA shows that emissions of '
        'methane, a powerful greenhouse gas and the major component of natural gas, are 70% higher than countries had '
        'claimed. Russia makes little or no attempt to capture methane from its oil and gas drilling, and to stop its '
        'pipelines leaking, so there are huge opportunities. If Putin were serious about tackling the climate crisis, '
        'Russia could provide an invaluable service to the rest of the world by plugging these leaks – reducing '
        'methane globally by a third by 2030 could reduce temperatures by 0.2C – and at current gas prices this could '
        'be done at no net cost and could even be profitable. Should the UK be fracking more, or producing more from '
        'the North Sea, to reduce dependency on Russian gas? No. Attempts to frack in the UK started more than a '
        'decade ago, but went nowhere, in part because of protests but also because the economics of industrial '
        'fracking in a densely populated country make it impractical. Any move to restart fracking now would take '
        'many years to produce any gas, long after the current gas price crisis has been forgotten. New licences for '
        'oil and gas exploration in the North Sea are also currently under consideration by the government, '
        'and on Thursday the Committee on Climate Change will publish its advice to ministers on whether these '
        'licences can be compatible with the UK’s climate goals. However, any newly licensed fields would also take '
        'years to come into production, so would have no impact on the current crisis. Bob Ward, policy director at '
        'the Grantham Research Institute on Climate Change at the London School of Economics, warns of falling for '
        'false solutions: “We know that some opponents of climate policy will try to hide the truth and instead fool '
        'the public into falsely believing that the soaring prices are due to green energy. If they are successful, '
        'they might slow down the transition to clean domestic energy.” Far more good could be done in the shorter '
        'term by insulating homes and ramping up renewable energy generation. What is the answer to the crisis? '
        'Rachel Kyte, dean of the Fletcher School at Tufts University in the US and an adviser to the UN '
        'secretary-general on the climate, says: “The west needs to meet Putin’s flagrant breach of international law '
        'with tough sanctions to force a change in calculus in Moscow. Putin believes he has to the largest extent '
        'sanction-proofed Russia, but Russia earns hundreds of millions of dollars a day from sales of oil and '
        'refined products, and more from sales of gas and minerals. “Weaning ourselves off these as quickly as '
        'possible is one route available to the west. In fact, Putin’s understanding of what decarbonisation would '
        'mean for Russian energy exports in the medium and long term may be a factor in the timing of Putin’s attack '
        'on Ukraine now.” Ending the use of fossil fuels is imperative, to reach net zero emissions and stave off the '
        'worst impacts of climate breakdown. But the shift will also create geopolitical tensions as the world’s '
        'massive fossil fuel exporters – Russia, Saudi Arabia and some other Middle Eastern countries, Latin American '
        'oil producers, Australia – begin to lose out economically. The crisis in Ukraine shows that some fossil fuel '
        'producers at least may not want to give up without a struggle the political leverage they gain from their '
        'resources.',
        'Western leaders have responded with fury to Russia’s “barbaric” military attacks on Ukrainian cities and '
        'vowed to hold the Kremlin to account for the invasion with a barrage of crippling sanctions. Shortly after '
        'reports broke of explosions near Kyiv, the US president, Joe Biden, accused his Russian counterpart, '
        'Vladimir Putin, of choosing a “premeditated war that will bring a catastrophic loss of life and human '
        'suffering”. “The prayers of the world are with the people of Ukraine tonight as they suffer an unprovoked '
        'and unjustified attack by Russian military forces,” he said.\n“Russia alone is responsible for the death and '
        'destruction this attack will bring, and the United States and its allies and partners will respond in a '
        'united and decisive way,” Biden said. “The world will hold Russia accountable.” Biden said he had spoken to '
        'the Ukrainian president, Volodymyr Zelenskiy, on the phone shortly after the attacks began, and said he had '
        'told him he and allied partners would be “imposing severe sanctions on Russia” once the G7 leaders had met '
        'on Thursday. “We will continue to provide support and assistance to Ukraine and the Ukrainian people.” A '
        'joint statement issued by the 27 heads of state and government of the EU warned Russia that they would later '
        'on Thursday agree on “further restrictive measures that will impose massive and severe consequences on '
        'Russia for its action, in close coordination with our transatlantic partners.” The UK prime minister, '
        'Boris Johnson, told the House of Commons that the UK and its allies would respond with “a massive package of '
        'sanctions” that will “hobble the Russian economy”. He said: “Ukraine is a country that for decades has '
        'enjoyed freedom and democracy and the right to choose its own destiny. We and the world cannot allow that '
        'freedom just to be snuffed out. We cannot and will not just look away.”\nA Downing Street spokesperson said '
        'the prime minister had told Ukraine’s president he hoped his forces could resist the onslaught. France’s '
        'president, Emmanuel Macron, who had made a last ditch effort to broker peace through a summit between Putin '
        'and Biden, was in contact with Zelenskiy on his mobile phone early on Thursday. He said: “France strongly '
        'condemns Russia’s decision to wage war on Ukraine. Russia must end its military operations immediately. '
        '“France stands in solidarity with Ukraine. It stands with the Ukrainians and works with its partners and '
        'allies to end the war.” In a statement, Germany’s chancellor, Olaf Scholz, said: “Germany condemns in the '
        'strongest possible terms this unscrupulous act by President Putin. Our solidarity goes out to Ukraine and '
        'its people.” The world “will not forget this day of shame”, Germany’s foreign minister, Annalena Baerbock, '
        'said.\nMario Draghi, Italy’s prime minister, who has until now been cautious over imposing the most '
        'hard-hitting sanctions on Russia, suggested the EU would be unified in an immediate and tough response. He '
        'said: “The Italian government condemns Russia’s attack on Ukraine. It is unjustified and unjustifiable. '
        '“Italy is close to the Ukrainian people and institutions in this dramatic moment. We are working with '
        'European and Nato allies to respond immediately, with unity and determination.” Japan’s prime minister, '
        'Fumio Kishida, said his government strongly condemned Russia’s one-sided aggression. A virtual meeting of '
        'the G7, the world’s seven biggest economies, Canada, France, Germany, Italy, Japan, the UK and the US, '
        'is scheduled for later on Thursday.\nUrsula von der Leyen and Charles Michel, the presidents of the European '
        'Commission and European Council, issued a joint statement in which they promised financial and humanitarian '
        'assistance for Kyiv and vowed to “impose massive and severe consequences on Russia for its action”. Von der '
        'Leyen said Putin was responsible “for bringing war back to Europe”, describing the Russian leader’s '
        'behaviour as “barbaric”, as she outlined the scale and scope of the punitive measures planned. She said: “We '
        'will hold President Putin accountable for that. With this package, we will target strategic sectors of the '
        'Russian economy by blocking their access to key technologies and markets. “We will weaken Russia’s economic '
        'base and its capacity to modernise. In addition, we will freeze Russian assets in the EU and stop the access '
        'of Russian banks to the European financial market.”\nEU leaders will meet in Brussels on Thursday evening to '
        'discuss the long-prepared “full monty” package of sanctions against Russia, which have been designed to '
        'cripple the country’s economy. They range from cutting Russia out of the Swift payment system that '
        'lubricates world trade, to imposing export controls on critical goods such as high-tech components that the '
        'country cannot replace in the fields of artificial intelligence and weaponry, quantum computers, lasers and '
        'space. The foreign ministers for Estonia, Latvia and Lithuania said in a joint statement that the agreed '
        'measures had to include “disengaging Russia from Swift”. They said: “We would need to urgently provide '
        'Ukrainian people with weapons, ammunition and any other kind of military support to defend itself.” Nato '
        'secretary general, Jens Stoltenberg, announced that an alliance summit will be held on Friday, with Finland '
        'and Sweden in attendance as non-members. He said: “It will be a new reality, a new Europe after the invasion '
        'we saw today” Following an emergency meeting of the North Atlantic council, the alliance’s political '
        'decision making body, new guidance had also been issued to to its military commanders to allow them to more '
        'quickly move military forces around Europe, he said. He said: “We have already increased and we are '
        'increasing the presence of Nato troops in the eastern part of the alliance. “We do not have Nato troops in '
        'Ukraine and we do not have plans to send Nato troops to Ukraine.”\nStoltenberg, speaking in Brussels, '
        'said that Russia was waging war with air and missile attacks, ground forces and special forces from multiple '
        'directions, targeting the military infrastructure and major urban centres. He said: “This is a brutal act of '
        'war. Our thoughts are with the brave people of Ukraine. “Sadly, what we have warned against for months has '
        'come to pass. Despite all calls on Russia to change course and tireless efforts to seek a diplomatic '
        'solution. “Peace in our continent has been shattered. We now have war in Europe, on a scale and of a type we '
        'thought belong to history. “This is a grave moment for the security of Europe.”\nSpain’s prime minister, '
        'Pedro Sánchez, tweeted: “The government of Spain condemns Russia’s aggression against Ukraine and expresses '
        'its solidarity with the Ukrainian government and its people. I remain in close contact with our partners and '
        'allies in the European Union and Nato to coordinate our response.” The United Nations secretary general '
        'António Guterres, who had urged Putin just before the assault began to stop his troops from attacking, '
        'tweeted an updated plea. “Under the present circumstances, I must change my appeal: President Putin, '
        'in the name of humanity, bring your troops back to Russia,” he said. “This conflict must stop now.”',
        'Top story: Kremlin invokes ‘demilitarisation’ as excuse Hello – Warren Murray introducing the news on a day '
        'we feared would come. Russian forces have attacked Ukraine on the orders of Vladimir Putin, who announced '
        'what he called a “special military operation” at dawn. Explosions and airstrikes have been heard this '
        'morning near major Ukrainian cities, including the capital, Kyiv, and air raid sirens went off. Our '
        'correspondent Luke Harding reported earlier: “At least seven ‘powerful’ airstrikes on Vasilkovsky airport '
        'outside Kyiv, where Ukraine’s military fighter bombers are kept, Kyiv command says.” The Ukraine foreign '
        'minister, Dmytro Kuleba, confirmed what he called the “full-scale invasion of Ukraine. Peaceful Ukrainian '
        'cities are under strikes.”\nIn a bid to justify the invasion, Putin branded Ukraine an “anti-Russia … '
        'created on our historic lands” and claimed the campaign was for the “demilitarisation and denazification” of '
        'Russia’s neighbour – echoing a false theme of Kremlin propaganda that the Kyiv government is controlled by '
        'the far right. Joe Biden said: “The prayers of the entire world are with the people of Ukraine tonight as '
        'they suffer an unprovoked and unjustified attack by Russian military forces. President Putin has chosen a '
        'premeditated war that will bring a catastrophic loss of life and human suffering.” Boris Johnson said: “I am '
        'appalled by the horrific events in Ukraine and I have spoken to President Zelenskiy to discuss next steps. '
        'President Putin has chosen a path of bloodshed and destruction by launching this unprovoked attack on '
        'Ukraine. The UK and our allies will respond decisively.” Here’s what we know so far about the Russian '
        'invasion. Make sure you keep up with the rapid developments in Ukraine at our live blog.\nAs Putin was '
        'speaking and the first detonations were reported, the UN security council was holding an emergency session, '
        'chaired by Russia itself, which holds the rotating presidency, and at which the Russian and Ukrainian '
        'representatives traded barbs. Ukraine’s president, Volodymyr Zelenskiy, earlier put out an address appealing '
        'directly to the Russian people to “listen to the voice of reason”. Russia’s leadership, he said, '
        'was “telling you that this flame will liberate the people of Ukraine, but the Ukrainian people are free”. He '
        'warned: “If someone attempts to take away our land, our freedom, our lives, the lives of our children, '
        'we will defend ourselves. By attacking, you will see our faces, not our backs, but our faces.”\nWith '
        'international condemnation growing, Russia’s defence minister, Sergei Shoigu, the commanders-in-chief of the '
        'Russian air force and Black Sea fleet, leading state “propagandists” and 351 Duma deputies are expected to '
        'be identified in EU sanctions that go further than the US, and further still than Boris Johnson’s Russia '
        'sanctions. Larry Elliott thinks that targeting Putin’s regime economically has mixed prospects: “Putin has '
        'been actively seeking to insulate Russia from the west ever since the invasion of the Crimea in 2014 … [and] '
        'Russia has used the money from its oil and gas exports to build up substantial financial defences. Moscow is '
        'sitting on foreign currency reserves of about $500bn (£369bn) and, by international standards, has extremely '
        'low levels of national debt.” The latter has a bearing on sanctions that stop Russia issuing or trading its '
        'sovereign debt in London and New York: the amount of bonds Russia needs to sell is relatively '
        'small.\nEurope’s dependence on gas from Russia looms large in all of this, of course. According to '
        'calculations by the Institute of Energy Economics at the University of Cologne shared with the Guardian, '
        'current levels of gas held in European reserves “could compensate for a loss of Russian deliveries” over the '
        'next six weeks unless temperatures were to drop dramatically in February or March. The US and other '
        'countries have said they are ready to step in with supplies of gas if Russia cuts Europe off. * * * Another '
        '10 years of debt – Students in England will have to continue paying back university loans over 40 years '
        'instead of 30. The number of graduates repaying in full is expected to double from under a quarter to more '
        'than half. They will face repayments sooner as the government cuts the wage threshold from £27,295 to £25,'
        '000 for new borrowers from September 2023. Martin Lewis, the founder of MoneySavingExpert.com, said: “It’s '
        'effectively a lifelong graduate tax for most.” Larissa Kennedy, president of the UK National Union of '
        'Students, said ministers were “saddling young people with unimaginable debt for the next 40 years of their '
        'lives”.\nIn a concession, interest rates on student loans will be slashed for new borrowers and set no '
        'higher than the rate of inflation from next year – but Labour’s shadow education secretary accused the '
        'government of delivering a stealth tax that hits those on low incomes hardest. The government is also '
        'launching consultations on introducing minimum eligibility requirements to access student loans; and a '
        'lifelong loan entitlement for the equivalent of four years of post-18 education. * * * Meat and cancer – '
        'Vegetarians have a 14% lower chance of developing cancer than meat eaters, according to a large study by '
        'Oxford researchers. Compared with people who eat meat more than five times a week, those who consumed small '
        'amounts had a 2% lower risk of cancer. The authors made clear that their findings did not conclusively prove '
        'regular meat-eating increased the risk of cancer. Smoking and body fat could also help explain the '
        'differences found, they said. Low meat eaters in the study had a 9% lower risk of developing bowel cancer '
        'than regular meat eaters. Vegetarian women were 18% less likely than those who ate meat regularly to develop '
        'postmenopausal breast cancer, though that may be due to their lower body mass index. Vegetarian men had a '
        '31% lower risk of prostate cancer, while among males who still ate fish it was 20% lower. * * * Starmer v '
        'Sunak – Keir Starmer will today pledge to “reimagine the role of government” as a partner to the private '
        'sector and take advantage of the opportunities of Brexit. Speaking in Huddersfield, the Labour leader will '
        'promise to value private companies as a partner to the state, and lay into Rishi Sunak and the Conservatives '
        'for “increasing taxes more than any other chancellor in half a century”. Labour’s strategy is for Starmer to '
        'drill issues such as tax and the cost of living to inflame Tory divisions and put Sunak in the spotlight '
        'given his ambitions to succeed Johnson as leader. Sunak will be delivering the annual Mais lecture at Bayes '
        'business school, in which he will say he wants to cut taxes “sustainably” and downgrade the role of the '
        'state as an engine of growth – aiming to quell concern among Tory backbenchers about the tax burden rising '
        'to its highest level in 70 years. * * * Ikea but it’s Lidl – Today, Ikea’s £170m experiment on the former '
        'Kings Mall in Hammersmith will be tested with the opening of Livat, its first city centre shopping mall '
        'globally and the first to be refurbished rather than built from scratch.\nIkea has 47 other shopping centres '
        'worldwide, but Livat is just over a third of the size of its typical site, and its first in the UK. It '
        'houses Ikea’s only high street store in the UK, a quarter the size of a typical store, as well as a Lidl, '
        'a Library of Things, and Sook, a rent-by-the hour retail or events space. Today in Focus podcast: Covid gets '
        'free rein Today marks the first day in nearly two years that no laws will be in place in England to deal '
        'with the spread of Covid-19. But is the government still following the science?\nLunchtime read: One '
        'person’s influence is someone else’s profit More and more young people are enticed by the glittering '
        'promises of a career as an influencer – but it’s usually someone else getting rich.\nSport Ralf Rangnick '
        'admitted Manchester United’s plan was in the “dustbin” after Atlético Madrid scored on seven minutes before '
        'Anthony Elanga’s second half equaliser snatched a draw for the interim manager’s team in the Champions '
        'League last-16 first leg. Antonio Conte has questioned whether he is the right manager to turn Tottenham’s '
        'fortunes around after Burnley inflicted their fourth defeat in five games. England manager Sarina Wiegman '
        'said her side have taken “lots of information” from their 3-1 victory against Germany and inaugural Arnold '
        'Clark Cup win but will not get carried away before the European Championship in the summer. In the Premier '
        'League, Liverpool hammered Leeds 6-0 at Anfield, with two goals each for Mohamed Salah and Sadio Mané and '
        'one apiece for Joël Matip and Virgil van Dijk. England coach Eddie Jones is expected to deploy Manu Tuilagi '
        'at centre for the Six Nations encounter with Wales, who have dropped Louis Rees-Zammit. After four Olympic '
        'Games, seven gold and two silver medals, Sir Jason Kenny, Britain’s most decorated Olympian, has announced '
        'his retirement. Joe Root has declined to divulge his role in the decision to drop Jimmy Anderson and Stuart '
        'Broad for the West Indies tour but said it does not shut the door on their record-breaking careers. And '
        'Lewis Hamilton has accused Formula One stewards of potential bias towards specific drivers and teams as old '
        'wounds were reopened on the first day of pre-season testing in Barcelona on Wednesday. Business Vladimir '
        'Putin’s decision to invade Ukraine has wreaked havoc on already-wobbly financial markets this morning with '
        'shares falling precipitously in Asia Pacific overnight. Hong Kong was the worst hit, down more than 3%, '
        'and the FTSE100 is set to shed around 2.5% at the opening bell. Brent crude soared past $100 a barrel in a '
        'sign of increasing nerves about the impact on supplies, the Russian rouble hit a record low and the Moscow '
        'stock exchange suspended trading on all markets. The US dollar strengthened on all the uncertainty and left '
        'the pound at $1.349 and €1.201. The papers The print editions were slightly overtaken by events today. The '
        'Guardian’s splash is “State of emergency in Ukraine as US warns Putin ready to invade”. “Welcome to hell” – '
        'the Mirror says that is the “warning from Ukraine” to Russian soldiers if they invade. But the Express says '
        'Putin is “Hell-bent” and has “gone full tonto” – the latter having been said by the UK defence secretary, '
        'Ben Wallace, and the former by Liz Truss, the foreign secretary. Wallace clearly had the better line: '
        '“Putin’s gone ‘full tonto’” is the Metro’s page one headline.\nThe Financial Times says “Brussels hits '
        'Putin’s inner circle as US hardens invasion warning”. The i has a front-page Ukraine picture overlaid with '
        '“State of emergency declared as nation feels ‘knot of fear’”. Its splash though is “Students to face '
        '‘lifelong graduate tax’”, the same story that leads the Times: “Students set to shoulder £100k bill for '
        'degrees”. “Sunak vows to slash tax burden” says the Telegraph, while at this moment the Mail is most worried '
        'about Britain’s spies being told, as it puts in its own words, to “go woke” by an internal guide to '
        'diversity and inclusion. The Sun says mock royal jewels from TV show The Crown have been stolen. Sign '
        'up\nThe Guardian Morning Briefing is delivered to thousands of inboxes bright and early every weekday. If '
        'you are not already receiving it by email, you can sign up here. For more news: www.theguardian.com Get in '
        'Touch If you have any questions or comments about any of our newsletters please email '
        'newsletters@theguardian.com Sign up to Inside Saturday to get an exclusive behind the scenes look at the top '
        'features from our new magazine delivered to your inbox every weekend',
        'It will go down as one of the most surreal sessions the United Nations chamber has ever witnessed, '
        'as the very war it was supposed to prevent broke out while it was sitting. Vladimir Putin, with brutal '
        'timing, delivered a speech announcing that Russia would start a “special military operation” in Ukraine – '
        'while an emergency session of the UN security council was under way. The secretary general, '
        'Antonio Guterres, was the first to speak, and at that time Putin’s intentions were not entirely clear. But '
        'Guterres pointed to the reports of troops moving into position, and did something notable and rare for a UN '
        'secretary general: he publicly called out the head of a security council permanent member. “If indeed an '
        'operation is being prepared, I have only one thing to say, from the bottom of my heart,” Guterres said. '
        '“President Putin: stop your troops from attacking Ukraine. Give peace a chance. Too many people have already '
        'died.”\nBy the time it was the turn of the Russian representative, Vasily Nebenzya, to speak, '
        'Putin had given his address, and there was no more mystery. Peace was not to be given a chance after all. '
        'Nebenzya, who had spent weeks deriding western states for their “hysterical” warnings of impending invasion, '
        'pivoted to argue it was not actually a war that was getting under way, but a “special military operation” to '
        'protect the people of the Donbass.\nThe Ukrainian ambassador, Sergiy Kyslytsya, had been waiting for his '
        'turn to speak while receiving constant updates from Kyiv. When his time came, he had to dispense with his '
        'prepared speech because, he said, “most of it is already useless”. Instead he held up a copy of the UN '
        'charter and read the clause that said UN membership was open to all peace-loving states that accepted the '
        'obligations contained in the small sky-blue booklet. “Russia is not able to carry out any of those '
        'obligations,” Kyslytsya declared. He challenged Nebenzya to deny that Ukraine was under attack. “You have a '
        'smartphone,” he said, taunting the Russian to check with his boss, the foreign minister, on what was really '
        'going on. “You can call Lavrov right now. We can make a pause to let you go out and call him.” Nebenzya '
        'declined. “I have already said all I know at this point,” he said. “Waking up minister Lavrov at this time '
        'is not something I plan to do.” An hour or so into the meeting, the multiplying reports of bombardment of '
        'Ukrainian cities had reached the chamber, and if the futility of the council’s calls for peace and dialogue '
        'had not been clear before, they were now agonisingly obvious. Some ambassadors demanded to speak for a '
        'second time to express their sense of betrayal. “At the exact time as we were gathered in the council '
        'seeking peace, Putin delivered a message of war in total disdain for the responsibility of this council,'
        '” said the US permanent representative, Linda Thomas-Greenfield. “This is a grave emergency.” Her British '
        'counterpart, Barbara Woodward, declared it “a grave day for Ukraine and for the principles of the United '
        'Nations”. Kyslytsya himself was trembling with emotion. He stared at Nebenzya and demanded the Russian '
        'relinquish his duties as chair of the council. “There is no purgatory for war criminals,” he warned him. '
        '“They go straight to hell.” At that point, Nebenzya quickly closed the meeting, claiming that Russia’s '
        'aggression was not directed at the Ukrainian people, but against what he called “the junta that is in power '
        'in Kiev”. Then he adjourned and left. A security council that had begun, just about, in peacetime, '
        'had broken up in a time of war, and perhaps at the start of a major conflict.']


if __name__ == '__main__':
    articles2 = [
        'one two three four five six seven eight nine ten',
        'one two three four five six seven eight nine ten eleven',
        'one two three four five six seven eight nine ten eleven twelve',
        'one two three four five six seven eight nine ten eleven twelve thirteen',
        'one two three four five six seven eight nine ten eleven twelve thirteen fourteen',
    ]

    articles = [
        'Ukraine’s president of the united states has made a desperate appeal to the Russian people of the united '
        'states, and the president of the united states.',
        'For many Russians of the united states, it was an unfamiliar sight to see the faces of the two leaders in an '
        'unfamiliar sight.',
        'The striped bats were hanging on their feet for best corpora alumni and ate best fishes COVID-19 am are is '
        'were was children that were striped with bands of sunlight and stripped from their things.'
    ]

    for index, article in enumerate(articles):
        print('Article %d: %d' % (index, compute_document_length(article)))
    average_document_length = compute_average_document_length(articles)
    print(round(average_document_length, 2))